In [32]:
import json
import numpy as np

In [25]:
graph = {
    'a': set('bcdef'),
    'b': set('ce'),
    'c': set('d'),
    'd': set('e'),
    'e': set('f'),
    'f': set('cgh'),
    'g': set('fh'),
    'h': set('fg')
}

In [29]:
a, b, c, d, e, f, g, h = range(8)
_ = float('inf')
# a b c d e f g h
W = [[0, 2, 1, 3, 9, 4, _, _],  # a
     [_, 0, 4, _, 3, _, _, _],  # b
     [_, _, 0, 8, _, _, _, _],  # c
     [_, _, _, 0, 7, _, _, _],  # d
     [_, _, _, _, 0, 5, _, _],  # e
     [_, _, 2, _, _, 0, 2, 2],  # f
     [_, _, _, _, _, 1, 0, 6],  # g
     [_, _, _, _, _, 9, 8, 0]]  # h

In [26]:
graph = {k: list(v) for k, v in graph.items()}
graph

{'a': ['b', 'c', 'd', 'f', 'e'],
 'b': ['c', 'e'],
 'c': ['d'],
 'd': ['e'],
 'e': ['f'],
 'f': ['c', 'h', 'g'],
 'g': ['f', 'h'],
 'h': ['f', 'g']}

In [27]:
with open("graph.json", "w") as f:
    s = json.dumps(graph)
    f.write(s)

In [35]:
import pandas as pd

In [43]:
data = pd.read_excel('./data/graph1.xlsx', index_col='row/col')

In [44]:
data

a    b    c    d    e    f    g    h
row/col                                        
a        0.0  2.0  1.0  3.0  9.0  4.0  NaN  NaN
b        NaN  0.0  4.0  NaN  3.0  NaN  NaN  NaN
c        NaN  NaN  0.0  8.0  NaN  NaN  NaN  NaN
d        NaN  NaN  NaN  0.0  7.0  NaN  NaN  NaN
e        NaN  NaN  NaN  NaN  0.0  5.0  NaN  NaN
f        NaN  NaN  2.0  NaN  NaN  0.0  2.0  2.0
g        NaN  NaN  NaN  NaN  NaN  1.0  0.0  6.0
h        NaN  NaN  NaN  NaN  NaN  8.0  9.0  0.0

In [45]:
data.fillna(float('inf'), inplace=True)

In [46]:
data

a    b    c    d    e    f    g    h
row/col                                        
a        0.0  2.0  1.0  3.0  9.0  4.0  inf  inf
b        inf  0.0  4.0  inf  3.0  inf  inf  inf
c        inf  inf  0.0  8.0  inf  inf  inf  inf
d        inf  inf  inf  0.0  7.0  inf  inf  inf
e        inf  inf  inf  inf  0.0  5.0  inf  inf
f        inf  inf  2.0  inf  inf  0.0  2.0  2.0
g        inf  inf  inf  inf  inf  1.0  0.0  6.0
h        inf  inf  inf  inf  inf  8.0  9.0  0.0

In [49]:
data['a']

row/col
a    0.0
b    inf
c    inf
d    inf
e    inf
f    inf
g    inf
h    inf
Name: a, dtype: float64

In [50]:
X = np.linspace(-4, 4, 200)
Y = np.linspace(-4, 4, 200)

In [52]:
a = np.meshgrid(X, Y)

In [56]:
a[0]

array([[-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ],
       [-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ],
       [-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ],
       ...,
       [-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ],
       [-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ],
       [-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ]])

In [53]:
import numpy as np
from scipy import spatial

In [54]:
distance_matrix = spatial.distance.cdist(a, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [63]:
from numpy import asarray


def meshgrid2(*arrs):
    arrs = tuple(reversed(arrs))
    lens = list(map(len, arrs))
    dim = len(arrs)
    sz = 1
    for s in lens:
        sz *= s
    ans = []
    for i, arr in enumerate(arrs):
        slc = [1] * dim
        slc[i] = lens[i]
        arr2 = asarray(arr).reshape(slc)
        for j, sz in enumerate(lens):
            if j != i:
                arr2 = arr2.repeat(sz, axis=j)
        ans.append(arr2)
    return tuple(ans)

In [64]:
g = meshgrid2(X, Y)
positions = np.vstack(map(np.ravel, g))

C:\Users\Den Ka\AppData\Local\Temp\ipykernel_15440\4214666909.py:2: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  positions = np.vstack(map(np.ravel, g))


In [65]:
positions

array([[-4.        , -4.        , -4.        , ...,  4.        ,
         4.        ,  4.        ],
       [-4.        , -3.95979899, -3.91959799, ...,  3.91959799,
         3.95979899,  4.        ]])

In [67]:
g = np.meshgrid([0, 1], [0, 1])
print(*zip(*(x.flat for x in g)))

(0, 0) (1, 0) (0, 1) (1, 1)


In [71]:
g = np.meshgrid(X, Y)
points_coordinate = list(zip(*(x.flat for x in g)))

In [74]:
points_coordinate

[(-4.0, -4.0),
 (-3.959798994974874, -4.0),
 (-3.919597989949749, -4.0),
 (-3.879396984924623, -4.0),
 (-3.8391959798994977, -4.0),
 (-3.798994974874372, -4.0),
 (-3.758793969849246, -4.0),
 (-3.7185929648241207, -4.0),
 (-3.678391959798995, -4.0),
 (-3.6381909547738696, -4.0),
 (-3.5979899497487438, -4.0),
 (-3.557788944723618, -4.0),
 (-3.5175879396984926, -4.0),
 (-3.477386934673367, -4.0),
 (-3.4371859296482414, -4.0),
 (-3.3969849246231156, -4.0),
 (-3.35678391959799, -4.0),
 (-3.3165829145728645, -4.0),
 (-3.2763819095477387, -4.0),
 (-3.2361809045226133, -4.0),
 (-3.1959798994974875, -4.0),
 (-3.1557788944723617, -4.0),
 (-3.115577889447236, -4.0),
 (-3.0753768844221105, -4.0),
 (-3.035175879396985, -4.0),
 (-2.9949748743718594, -4.0),
 (-2.9547738693467336, -4.0),
 (-2.914572864321608, -4.0),
 (-2.8743718592964824, -4.0),
 (-2.834170854271357, -4.0),
 (-2.7939698492462313, -4.0),
 (-2.7537688442211055, -4.0),
 (-2.7135678391959797, -4.0),
 (-2.6733668341708543, -4.0),
 (-2.6331

In [72]:
distance_matrix = spatial.distance.cdist(points_coordinate, points_coordinate, metric='euclidean')

In [73]:
distance_matrix

array([[ 0.        ,  0.04020101,  0.08040201, ..., 11.25699926,
        11.2853179 , 11.3137085 ],
       [ 0.04020101,  0.        ,  0.04020101, ..., 11.22875313,
        11.25699926, 11.2853179 ],
       [ 0.08040201,  0.04020101,  0.        , ..., 11.20058006,
        11.22875313, 11.25699926],
       ...,
       [11.25699926, 11.22875313, 11.20058006, ...,  0.        ,
         0.04020101,  0.08040201],
       [11.2853179 , 11.25699926, 11.22875313, ...,  0.04020101,
         0.        ,  0.04020101],
       [11.3137085 , 11.2853179 , 11.25699926, ...,  0.08040201,
         0.04020101,  0.        ]])

In [75]:
x = y = [1, 2, 3, 4, 5]

In [80]:
sum(map(lambda a, b: a * b, x, y))

55

In [79]:
sum([1, 4, 9, 16, 25])

55